#!/bin/bash
function getip() {
    ip=$(curl -d "token=$1&data=$2" http://gewu.me/ecard/$3 2>/dev/null)
    if [ -z "$ip" ]; then
        echo -n "not found";
    else
        echo -n "$ip";
    fi
}

if [ "$1" == "test" ]; then
    token="MUp0JBjFn5LNgWPfFNQT"
elif [ "$1" == "2" ]; then
    token="i18koB6w1NjGKQAQSOKa"
else
    echo "usage: queryip (test | 2)"
    exit 1
fi

echo "        LOCAL IP         VPN IP           last report"
echo "master  $(getip $token master queryip)    $(getip $token master queryvpnip)    $(getip $token master queryip_lastreport)"
echo "slave   $(getip $token slave queryip)    $(getip $token slave queryvpnip)    $(getip $token slave queryip_lastreport)"

